version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-agpa
    environment:
      MYSQL_DATABASE: agpa  
      MYSQL_USER: agpa
      MYSQL_PASSWORD: agpa
      MYSQL_ROOT_PASSWORD: agpa
    ports:
      - "3306:3306"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-agpa
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: agpa
      PMA_PASSWORD: agpa
    ports:
      - "8080:80"
    
  web:
    build: ./
    container_name: php-agpa
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    links:
      - mysql